import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/core/navbar";
import { useWallet } from "@solana/wallet-adapter-react";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const WalletConnectionProvider = dynamic(
  () => import("./context/WalletConnectionProvider"),
  {
    ssr: false,
  }
);




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <WalletConnectionProvider>
    <html lang="en">
      <body className={`${inter.className}`}>
        <NavBar />
        {children}
      </body>

    </html>
  );
}
