import dynamic from "next/dynamic";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/core/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const WalletConnectionProvider = dynamic(
  () => import("./context/WalletConnectionProvider"),
  {
    ssr: false,
  }
);


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <WalletConnectionProvider>
          <Navbar />
          {children}
        </WalletConnectionProvider>
      </body>
    </html>
  );
}
